// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BoxOfficeDemo.Server.Models
{
    //public partial class Movie
    //{
    //    public Movie()
    //    {
    //        Reviews = new HashSet<Review>();
    //        WatchLists = new HashSet<WatchList>();
    //    }

    //    [Key]
    //    [Column(TypeName = "decimal(28, 8)")] 
    //    public decimal? MovieID { get; set; }
    //    [Required]
    //    [StringLength(100)]
    //    public string? MovieName { get; set; }
    //    [StringLength(100)]
    //    public string? Image { get; set; }
    //    public string? Description { get; set; }
    //    [Column(TypeName = "date")]
    //    public DateTime? ReleasedDate { get; set; }
    //    public int? ParentalGuide { get; set; }
    //    public TimeSpan? Length { get; set; }
    //    [StringLength(50)]
    //    public string? Genere { get; set; }
    //    [Column(TypeName = "decimal(3, 1)")]
    //    public decimal? Rate { get; set; }
    //    [StringLength(50)]
    //    public string? Director { get; set; }
    //    [StringLength(50)]
    //    public string? Writer { get; set; }
    //    public string? Stars { get; set; }

    //    [InverseProperty("Movie")]
    //    public virtual ICollection<Review> Reviews { get; set; }

    //    [InverseProperty("Movie")]
    //    public virtual ICollection<WatchList> WatchLists { get; set; }
    //}
    public partial class Movie
    {
        public Movie()
        {
            Reviews = new HashSet<Review>();
            WatchList = new HashSet<WatchList>();
        }

        [Key]
        [Column(TypeName = "decimal(28, 8)")]
        public decimal MovieID { get; set; }
        [Required]
        [StringLength(100)]
        public string MovieName { get; set; }
        //[StringLength(100)]
        public string Image { get; set; }
        public string Description { get; set; }
        [Column(TypeName = "date")]
        public DateTime? ReleasedDate { get; set; }
        public int? ParentalGuide { get; set; }
        public TimeSpan? Length { get; set; }
        [StringLength(50)]
        public string Genere { get; set; }
        [Column(TypeName = "decimal(3, 1)")]
        public decimal? Rate { get; set; }
        [StringLength(50)]
        public string Director { get; set; }
        [StringLength(50)]
        public string Writer { get; set; }
        public string Stars { get; set; }

        [InverseProperty("Movie")]
        public virtual ICollection<Review> Reviews { get; set; }
        [InverseProperty("Movie")]
        public virtual ICollection<WatchList> WatchList { get; set; }
    }
}