// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace BoxOfficeDemo.Server.Models
{
    public partial class User : IdentityUser
    {
        public User()
        {
            Reviews = new HashSet<Review>();
            WatchLists = new HashSet<WatchList>();
        }

        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string? RefreshToken { get; set; }
        public DateTime? RefreshTokenExpiryTime { get; set; }

        [InverseProperty("User")]
        public virtual ICollection<Review> Reviews { get; set; }

        [InverseProperty("User")]
        public virtual ICollection<WatchList> WatchLists { get; set; }
    }
}