// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BoxOfficeDemo.Server.Models
{
    public partial class WatchList
    {
        [Key]
        [Column(TypeName = "decimal(28, 8)")]
        public decimal Id { get; set; }
        public string UserID { get; set; }

        [Column(TypeName = "decimal(28, 8)")] 
        public decimal MovieID { get; set; }

        [ForeignKey("MovieID")]
        [InverseProperty("WatchLists")]
        public virtual Movie Movie { get; set; }

        [ForeignKey("UserID")]
        [InverseProperty("WatchLists")]
        public virtual User User { get; set; }
    }
}