// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BoxOfficeDemo.Server.Models
{
    //public partial class WatchList
    //{
    //    [Key]
    //    [Column(TypeName = "decimal(28, 8)")]
    //    public decimal Id { get; set; }
    //    public string UserID { get; set; }

    //    [Column(TypeName = "decimal(28, 8)")] 
    //    public decimal MovieID { get; set; }

    //    [ForeignKey("MovieID")]
    //    [InverseProperty("WatchLists")]
    //    public virtual Movie Movie { get; set; }

    //    [ForeignKey("UserID")]
    //    [InverseProperty("WatchLists")]
    //    public virtual User User { get; set; }
    //}
    [Index("MovieID", Name = "IX_WatchList_MovieID")]
    [Index("UserID", Name = "IX_WatchList_UserID")]
    public partial class WatchList
    {
        [Required]
        public string UserID { get; set; }
        [Column(TypeName = "decimal(28, 8)")]
        public decimal MovieID { get; set; }
        [Key]
        [Column(TypeName = "decimal(28, 8)")]
        public decimal Id { get; set; }
        public DateTime? AddedDate { get; set; }
        [ForeignKey("MovieID")]
        [InverseProperty("WatchList")]
        public virtual Movie Movie { get; set; }
        [ForeignKey("UserID")]
        [InverseProperty("WatchList")]
        public virtual User User { get; set; }
    }
}